project_id = "hwbxvrewiapyhjceabvw"

[functions.create-checkout]
verify_jwt = false

[functions.customer-portal]
verify_jwt = false

[functions.stripe-webhook]
verify_jwt = false

[functions.send-welcome-email]
verify_jwt = false

[functions.email-hook]
verify_jwt = false

[functions.create-org-user]
verify_jwt = false

[functions.reset-password-request]
verify_jwt = false

[functions.whatsapp-instance-checkout]
verify_jwt = true

[functions.whatsapp-multiattendant-webhook]
verify_jwt = false

[functions.wasenderapi-instance-manager]
verify_jwt = true

[functions.whatsapp-send-message]
verify_jwt = true

[functions.whatsapp-presence-update]
verify_jwt = true

[functions.whatsapp-media-proxy]
verify_jwt = false

[functions.whatsapp-create-upload-url]
verify_jwt = true

[functions.whatsapp-webhook]
verify_jwt = false

[functions.whatsapp-send]
verify_jwt = true
