project_id = "hwbxvrewiapyhjceabvw"

[functions.create-checkout]
verify_jwt = false

[functions.send-welcome-email]
verify_jwt = false

[functions.stripe-webhook]
verify_jwt = false

[functions.email-hook]
verify_jwt = false
